spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mdd?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: admin1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
server:
  port: 9000
  servlet:
    context-path: /api/

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem